### ISSUE TITLE
possible bug with pandas and indexing for base_params

### ISSUE THREAD

**Issue by evilantal** [dataiku/dss-plugin-generalized-linear-models#15]
**Describe the bug**
I was getting IndexError/KeyError when running the GLM Summary View on a model trained with this plugin.
I traced it back to this line of code in graph_utils.py (line 17)

`base_params = {col: train_df[col].mode()[0] for col in train_df.columns}`

This generated IndexErrors from pandas for col.

![Capture](https://user-images.githubusercontent.com/13693562/164711872-541d68bb-e945-4b29-a2e9-81e8b4206009.PNG)
[error log.txt](https://github.com/dataiku/dss-plugin-generalized-linear-models/files/8540870/error.log.txt)

I managed to fix it by indexing train_df with column indexes instead of names by replacing this line with:
`base_params = {col: train_df.iloc[idx].mode()[0] for idx, col in enumerate(train_df.columns)}`

**To Reproduce**
1. Install Generalized Linear Models plugin with default package requirements (except Werkzeug==2.0.3, see issue #14 )
2. Train a model using a Generalized Linear Models plugin algorithm
3. Go into the odel summary page
4. Select "GLM Summary" from the Views
5. IndexError pops up related to the above line and pandas

**Additional context**
 - Browser: chrome
 - DSS version: 10.0.4
 - pandas==1.0.5

**Comment by david-behar** [comment]
I will look into this. I don't get the error on the datasets/analysis I have, can you provide a small project where the bug appears?
